defaults:
  - _self_
  - data: ???
  - model: ???
  - trainer: bb

# One of: fit | validate | test. Defaults to fit.
# `ckpt_path` is required for validate / test; optional for fit (to resume).
mode: fit
ckpt_path: null

hydra:
  job:
    chdir: false
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
