_target_: nablafx.BlackBoxSystem
lr: 0.005
use_callbacks: true
log_media_every_n_steps: 3000
model:
  _target_: nablafx.BlackBoxModel
  processor:
    _target_: nablafx.processors.tcn.TCN
    num_inputs: 1
    num_outputs: 1
    num_controls: 0
    num_blocks: 10
    kernel_size: 3
    dilation_growth: 2
    channel_width: 16
    channel_growth: 1
    stack_size: 12
    groups: 1
    bias: true
    causal: true
    batchnorm: false
    residual: true
    direct_path: false
    cond_type: null
    cond_block_size: 128
    cond_num_layers: 1
    act_type: tanh
loss:
  _target_: nablafx.evaluation.FlexibleLoss
  losses:
  - name: l1_loss
    weight: 0.5
    alias: l1
  - name: mrstft_loss
    weight: 0.5
    alias: mrstft
